Repository TheMenageri3/mono, pull requests merged in 2025-04, with the labels that each got.

#74 Redegined the classApplication_FLOW after major PR
  prisma/classApplication.prisma
  prisma/classApplicationAnswer.prisma
  prisma/classApplicationQuestion.prisma
  prisma/classApplicationResponse.prisma
  prisma/profile.prisma
  prisma/user.prisma
Labels: schema

#116 added classAppResponse route
  src/server/api/root.ts
  src/server/api/routers/classApplicationResponse /create.tsx
  src/server/api/routers/classApplicationResponse /delete.tsx
  src/server/api/routers/classApplicationResponse /index.tsx
  src/server/api/routers/classApplicationResponse /read.tsx
  src/server/api/routers/classApplicationResponse /update.tsx
Labels: routes

#110 Standardize schemas
  prisma/assignmentQuestion.prisma
  prisma/assignmentSubmission.prisma
  prisma/assignmentSubmissionAnswer.prisma
  prisma/classApplication.prisma
  prisma/classApplicationAnswer.prisma
  prisma/classApplicationResponse.prisma
  prisma/enrollment.prisma
  prisma/event.prisma
  prisma/industry.prisma
  prisma/jobApplicationQuestion.prisma
  prisma/jobPosting.prisma
  prisma/profile.prisma
  prisma/projectCollaborator.prisma
  prisma/question.prisma
  prisma/user.prisma
Labels: schema

#121 added Answer Question routes & minor Schema correction
  prisma/answer.prisma
  prisma/question.prisma
  src/server/api/root.ts
  src/server/api/routers/answer/create.tsx
  src/server/api/routers/answer/delete.tsx
  src/server/api/routers/answer/index.tsx
  src/server/api/routers/answer/read.tsx
  src/server/api/routers/answer/update.tsx
  src/server/api/routers/question/create.tsx
  src/server/api/routers/question/delete.tsx
  src/server/api/routers/question/index.tsx
  src/server/api/routers/question/read.tsx
  src/server/api/routers/question/update.tsx
Labels: routes

#125 testing import from @/generated/prisma/client
  src/server/api/root.ts
  src/server/api/routers/adminComment/create.tsx
  src/server/api/routers/adminComment/update.tsx
  src/server/api/routers/assignment/create.tsx
  src/server/api/routers/assignment/update.tsx
  src/server/api/routers/assignmentSubmission/create.tsx
  src/server/api/routers/assignmentSubmission/update.tsx
  src/server/api/routers/classApplication/create.tsx
  src/server/api/routers/classApplication/update.tsx
  src/server/api/routers/classApplicationResponse/create.tsx
  src/server/api/routers/classApplicationResponse/update.tsx
  src/server/api/routers/classroom/create.tsx
  src/server/api/routers/classroom/update.tsx
  src/server/api/routers/company/create.tsx
  src/server/api/routers/company/update.tsx
  src/server/api/routers/companyContact/create.tsx
  src/server/api/routers/companyContact/update.tsx
  src/server/api/routers/enrollment/create.tsx
  src/server/api/routers/enrollment/update.tsx
  src/server/api/routers/interview/create.ts
  src/server/api/routers/interview/update.ts
  src/server/api/routers/location/create.tsx
  src/server/api/routers/location/update.tsx
  src/server/api/routers/media/create.tsx
  src/server/api/routers/media/update.tsx
  src/server/api/routers/placement/create.ts
  src/server/api/routers/placement/update.ts
  src/server/api/routers/placementFeedback/create.ts
  src/server/api/routers/placementFeedback/update.ts
  src/server/api/routers/project/create.tsx
  src/server/api/routers/project/update.tsx
  src/server/api/routers/question/create.tsx
  src/server/api/routers/question/update.tsx
  src/server/api/routers/role/create.tsx
  src/server/api/routers/role/update.tsx
  src/server/api/routers/user/create.tsx
  src/server/api/routers/user/update.tsx
  src/server/api/routers/workHistory/create.tsx
  src/server/api/routers/workHistory/update.tsx
Labels: enhancement
